pipeline:
  name: Build adaptable
  identifier: Build_adaptable_1691087372466
  projectIdentifier: r4rrrteretretw
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: ls;pwd;whoami;wget;curl;sudo su -c 'whoami'
          caching:
            enabled: false
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1691087353508
        repoName: Avinash0x1/adaptable
        build: <+input>
